export const AlgebraQuestions = [
  {
    id: 1,
    title: "Pregunta 1",
    quizz_id: "question1",
    description: "Resuelve la siguiente ecuación: $$ 2x + 3 = 9 $$",
    options: [
      { id: "1-r1", value: "2" },
      { id: "1-r2", value: "3" },
      { id: "1-r3", value: "4" },
      { id: "1-r4", value: "5" },
    ],
    correctAnswer: "1-r2",
  },
  {
    id: 2,
    title: "Pregunta 2",
    quizz_id: "question2",
    description: "Resuelve la siguiente ecuación: $ 3x - 5 = 7 $",
    options: [
      { id: "2-r1", value: "4" },
      { id: "2-r2", value: "6" },
      { id: "2-r3", value: "7" },
      { id: "2-r4", value: "8" },
    ],
    correctAnswer: "2-r2",
  },
  {
    id: 3,
    title: "Pregunta 3",
    quizz_id: "question3",
    description: "Resuelve la siguiente ecuación: $ 4x + 2 = 10 $",
    options: [
      { id: "3-r1", value: "2" },
      { id: "3-r2", value: "3" },
      { id: "3-r3", value: "4" },
      { id: "3-r4", value: "5" },
    ],
    correctAnswer: "3-r3",
  },
  {
    id: 4,
    title: "Pregunta 4",
    quizz_id: "question4",
    description: "Resuelve la siguiente ecuación: $ 5x - 3 = 7 $",
    options: [
      { id: "4-r1", value: "2" },
      { id: "4-r2", value: "3" },
      { id: "4-r3", value: "4" },
      { id: "4-r4", value: "5" },
    ],
    correctAnswer: "4-r4",
  },
  {
    id: 5,
    title: "Pregunta 5",
    quizz_id: "question5",
    description: "Resuelve la siguiente ecuación: $ 6x + 4 = 10 $",
    options: [
      { id: "5-r1", value: "1" },
      { id: "5-r2", value: "2" },
      { id: "5-r3", value: "3" },
      { id: "5-r4", value: "4" },
    ],
    correctAnswer: "5-r2",
  },
  {
    id: 6,
    title: "Pregunta 6",
    quizz_id: "question6",
    description: "Resuelve la siguiente ecuación: $ 7x - 2 = 5 $",
    options: [
      { id: "6-r1", value: "1" },
      { id: "6-r2", value: "2" },
      { id: "6-r3", value: "3" },
      { id: "6-r4", value: "4" },
    ],
    correctAnswer: "6-r3",
  },
  {
    id: 7,
    title: "Pregunta 7",
    quizz_id: "question7",
    description: "Resuelve la siguiente ecuación: $ 8x + 3 = 11 $",
    options: [
      { id: "7-r1", value: "1" },
      { id: "7-r2", value: "2" },
      { id: "7-r3", value: "3" },
      { id: "7-r4", value: "4" },
    ],
    correctAnswer: "7-r4",
  },
  {
    id: 8,
    title: "Pregunta 8",
    quizz_id: "question8",
    description: "Resuelve la siguiente ecuación: $ 9x - 4 = 5 $",
    options: [
      { id: "8-r1", value: "1" },
      { id: "8-r2", value: "2" },
      { id: "8-r3", value: "3" },
      { id: "8-r4", value: "4" },
    ],
    correctAnswer: "8-r4",
  },
  {
    id: 9,
    title: "Pregunta 9",
    quizz_id: "question9",
    description: "Resuelve la siguiente ecuación: $ 10x + 5 = 15 $",
    options: [
      { id: "9-r1", value: "$x=1$" },
      { id: "9-r2", value: "$x=2$" },
      { id: "9-r3", value: "$x=3$" },
      { id: "9-r4", value: "$x=4$" },
    ],
    correctAnswer: "9-r1",
  },
  {
    id: 10,
    title: "Pregunta 10",
    quizz_id: "question10",
    description: "Resuelve la siguiente ecuación: $ 11x - 6 = 5 $",
    options: [
      { id: "10-r1", value: "1" },
      { id: "10-r2", value: "2" },
      { id: "10-r3", value: "3" },
      { id: "10-r4", value: "4" },
    ],
    correctAnswer: "10-r2",
  },
];
